### ISSUE TITLE
 Hash Algorithm Open Source

### ISSUE THREAD

**Issue by RiseofRice** [cryptic-game/cryptic-user#1]
hard security breach in user.py:line92

**Comment by RiseofRice** [comment]
change hash algorithm to ```hashlib.pbkdf2_hmac``` or ```hashlib.scrypt``` 
[Docs](https://docs.python.org/3/library/hashlib.html)

**Comment by ghost** [comment]
This feature was implemented in experimental in e06a0df994738f26be6287194e0c7291f81cac42 and merged into the master with #2.
